[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = False
admin_passwd = $pbkdf2-sha512$600000$Semd837vHUMIYYyRco4RYg$JAZuQSmEfiHeDwTQ/VWHp9K3OO1bPh0y003zXuV2zwFIxRJjezceJigJOws1jnSo/dK.g0ovIDhE9JDJj46uKw
log_level = info
dev_mode = all